backend:
  name: git-gateway
  branch: master # branch to update (optional, defaults to master)
  #name: github
  #repo: retrocede/krystalconsiders
publish_mode: editorial_workflow # enables editorial workflow (draft/approval/publish)
media_folder: "static/uploads" #  media uploads stored in repo under assets/uploads
public_folder: "/images/uploads" # where the images are in the url
collections:
  - name: "posts" # used in routes
    label: "Post" # used in UI
    folder: "content/posts" # The path to the folder where the documents are stored.
    create: true # should users be allowed to create new items in this collection?
    slug: "{{ year }}-{{ slug }}" # Filename template, eg YYYY-title.md
    fields: # the fields for each document
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
